const products = [
  {
    id: 1,
    name: "Wireless Mouse",
    category: "Electronics",
    description: "Ergonomic wireless mouse with 1600 DPI.",
    price: 599,
    image: "https://cdn.mos.cms.futurecdn.net/K4vRahcy6fpWqWm3VZCZEW.jpg",
    quantity:3,
  },
  {
    id: 2,
    name: "Bluetooth Headphones",
    category: "Electronics",
    description: "Bluetooth head phones with noise cancellation.",
    price: 1999,
    image: "https://hips.hearstapps.com/hmg-prod/images/best-noise-cancelling-headphones-comp-681c71e030784.jpg?crop=0.8888888888888888xw:1xh;center,top&resize=1200:*",
      quantity:50,
  },
  {
    id: 3,
    name: "Running Shoes",
    category: "Footwear",
    description: "Lightweight running shoes for men and women.",
    price: 2499,
    image: "https://post.healthline.com/wp-content/uploads/2022/04/2065446-Clone-The-12-Best-Running-Shoes-for-Wide-Feet-in-2022-1296x728-Header-c0dcdf.jpg",
      quantity:5,
  },
  {
    id: 4,
    name: "Water Bottle",
    category: "Accessories",
    description: "1 litre stainless steel water bottle.",
    price: 399,
    image: "https://specials-images.forbesimg.com/imageserve/6563f3861b52a9696eb28bd9/Best-Deals-From-The-Hydro-Flask-Cyber-Monday-Sale-Forbes/960x0.jpg?fit=scale",
    quantity:2,
  },
  {
    id: 5,
    name: "Backpack",
    category: "Accessories",
    description: "Durable backpack with multiple compartments.",
    price: 1499,
    image: "https://i5.walmartimages.com/dfw/4ff9c6c9-c147/k2-_eb8593a4-f607-4e34-91bb-85f16235e672.v1.jpg?odnHeight=318&odnWidth=568&odnBg=&odnDynImageQuality=70",
    quantity:2,
  },
  {
    id: 6,
    name: "Smart Watch",
    category: "Electronics",
    description: "Fitness tracking smartwatch with heart rate.",
    price: 3499,
    image: "https://www.hindustantimes.com/ht-img/img/2023/12/20/1600x900/71tTnJS25nL_SX679__cleanup_1703069824200_1703069824546.jpg",
    quantity:4,
  },
  {
    id: 7,
    name: "Sunglasses",
    category: "Accessories",
    description: "UV-protected stylish sunglasses.",
    price: 799,
    image: "https://d3995ea24pmi7m.cloudfront.net/media/catalog/product/M/8/M8017GR2V_1_lar.jpg",
      quantity:25,
  },
  {
    id: 8,
    name: "Leather Wallet",
    category: "Accessories",
    description: "Genuine leather wallet with card slots.",
    price: 699,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlbrtsCVj7PlgCv9a-APBEwo2yn8BdoprM9g&s",
      quantity:15,
  },
  {
    id: 9,
    name: "Notebook",
    category: "Stationery",
    description: "Hardcover ruled notebook with 200 pages.",
    price: 249,
    image: "https://cdn.mos.cms.futurecdn.net/AifzT4vmX5mkf7mGV5MoVT-1200-80.jpg",
      quantity:23,
  },
  {
    id: 10,
    name: "Ball Pen Set",
    category: "Stationery",
    description: "Pack of 10 smooth ball pens for your good handwritting.",
    price: 149,
    image: "https://www.rapiddeliveryservices.in/uploads/webp/rapiddeliveryservices/gold_point_ball_pen_blue_62735-.webp",
      quantity:11,
  },
  {
    id: 11,
    name: "Ceramic Mug",
    category: "Home & Kitchen",
    description: "Printed ceramic coffee mug.",
    price: 299,
    image: "https://a.storyblok.com/f/165154/1280x720/4df8ebe56b/1_hero-image.jpg/m/",
      quantity:10,
  },
  {
    id: 12,
    name: "Desk Lamp",
    category: "Home & Kitchen",
    description: "Adjustable LED desk lamp.",
    price: 999,
    image: "https://www.orangetree.in/cdn/shop/articles/esna-study-table-lamp.jpg?v=1722849647",
      quantity:19,
  },
  {
    id: 13,
    name: "Yoga Mat",
    category: "Fitness",
    description: "Non-slip yoga mat for home workouts.",
    price: 799,
    image: "https://www.cnet.com/a/img/resize/ade06cba6050b2e21b7a9d0942ef5e082688d429/hub/2022/08/12/c417b1b6-f63d-4870-ab2b-9bc07af73ba6/gettyimages-733474417.jpg?auto=webp&fit=crop&height=675&width=1200",
      quantity:17,
  },
  {
    id: 14,
    name: "T-shirt",
    category: "Apparel",
    description: "Cotton round neck t-shirt.",
    price: 499,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRb0avBsDzVpdCeZ28ENrR-zF_OTeM5S3CG0Q&s",
      quantity:8,
  },
  {
    id: 15,
    name: "Jeans",
    category: "Apparel",
    description: "Comfort-fit denim jeans for man and woman.",
    price: 1199,
    image: "https://5.imimg.com/data5/WW/VL/XN/SELLER-69111335/branded-mens-jeans-stock-lot-500x500.jpg",
      quantity:42,
  },
  {
    id: 16,
    name: "Table Clock",
    category: "Home & Kitchen",
    description: "Analog table clock with alarm.",
    price: 349,
    image: "https://m.media-amazon.com/images/I/81AGx-TUMYL.jpg?odnHeight=117&odnWidth=117&odnBg=FFFFFF",
      quantity:20,
  },
  {
    id: 17,
    name: "Power Bank",
    category: "Electronics",
    description: "10000mAh portable power bank.",
    price: 1299,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQW2baK70aFWgZWx9Va9APDqxkv_2cNOXF4xA&s",
      quantity:8,
  },
  {
    id: 18,
    name: "Earphones",
    category: "Electronics",
    description: "In-ear wired earphones with mic.",
    price: 399,
    image: "https://i.ytimg.com/vi/M47XjRTUywg/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBg_LvL5EWeFn9ZpM54WKcF9FyUuQ",
      quantity:21,
  },
  {
    id: 19,
    name: "Sports Bottle",
    category: "Fitness",
    description: "Squeeze sports water bottle.",
    price: 249,
    image: "https://image.made-in-china.com/365f3j00AMiqJlnrPykD/350-500-600ml-Soft-Touch-Custom-Logo-Double-Wall-Insulated-Sport-Travel-Outdoor-Stainless-Steel-Water-Bottle.webp",
      quantity:17,
  },
  {
    id: 20,
    name: "Gaming Keyboard",
    category: "Electronics",
    description: "Mechanical RGB gaming keyboard.",
    price: 2499,
    image: "https://knowtechie.com/wp-content/uploads/2022/10/das-keyboard-6-professional-main.jpg",
    quantity:9,
  }
];

export default products;
